### PR TITLE
[macOS] .FCStd file type added to allow Quicklook to work

### PR DESCRIPTION
**Pull request by MatthiasWM**
This Pull Request is in addition to my PR in FreeCAD: [7491](https://github.com/FreeCAD/FreeCAD/pull/7491)

This PR gives files ending in `.FCStd` the file type `org.freecad.fcstd`, which in turn makes it visible for QuickLook (and SpotLight and possibly other apps). If my other PR is applied, FC bundles that are built with Conda should then support QuickLook.

Even if my FC PR is not applied, it would still make `.FCStd` files visible for an external QL plugin. Either way, applying this PR should not do any harm.

### CODE REVIEW

**Comment by MatthiasWM** [comment]
Suspended! I will have to do some updates to make this work with Conda.

**Comment by luzpaz** [comment]
This is a great feature, thank you for dedicating time to it!

**Comment by MatthiasWM** [comment]
Today's commit adds a line to the build script that will move the QuickLook plugin into its final directory within the Bundle. This does not harm the build (except for an error message) if no QL plugin exists in the Conda archive. The corresponding PR in FreeCAD/FreeCAD was updated as well and tested with Conda/Mamba on M1 Monterey.

**Comment by MatthiasWM** [comment]
Adding support for `.FCMat` and `.FCParam` files, showing an FC document icon. Adding support for `'FCMacro` and `.FCScript` files, showing a newly added FC script icon.

**Comment by luzpaz** [comment]
Great!

**Comment by luzpaz** [comment]
@looooo can you merge this now that https://github.com/FreeCAD/FreeCAD/pull/7491 is merged ?

**Pull request merged**
