### PR TITLE
Use a launcher app to fix Apple's architecture detection.

### PR DESCRIPTION
**Pull request by oursland**
@adrianinsaval This will resolve the Apple architecture detection issues which incorrectly trigger Rosetta 2 on Apple silicon platforms.  This is the architecture-specific version.

The Universal Binaries version is on https://github.com/FreeCAD/FreeCAD-Bundle/pull/289 .

### CODE REVIEW

**Comment by adrianinsaval** [comment]
This is a better solution than #289 IMO, thanks!

**Comment by adrianinsaval** [comment]
huh, that's weird ci didn't show an error for the macos-13 workflow but it actually fails. It seems it does not have ninja installed

**Comment by luzpaz** [comment]
Will this be reverted or fixed soon. macOS tickets are going to keep getting reported

**Comment by oursland** [comment]
@luzpaz A fix is available in https://github.com/FreeCAD/FreeCAD-Bundle/pull/293

**Pull request merged**
