### PR TITLE
Icon and Desktop files

### PR DESCRIPTION
**Pull request by leoheck**
Attempt to fix the missing Icon and update the Application name from `Freecad Conda` to `Freecad Weekly`

Extra minor improvements.
- Disable execution flag on text files and images
- Add execution flag on a script `create_bundle.sh`
- Normalize indentation of the `create_bundle.sh`
- Normalize `echo's` with an upper case in the first character.

> NOTE: This was not tested since I don't have `conda` here on my system. And I could not install it quickly since it may be missing from my pre-released Ubuntu 22.04.

### CODE REVIEW

**Comment by luzpaz** [comment]
Activated checks to see what they spit out.

**Comment by luzpaz** [comment]
@looooo do you mind weighing in?

**Comment by looooo** [comment]
I guess we should modify the workflow files to not delete/upload anything for PR's

**Comment by leoheck** [comment]
@looooo sure, let me try here.

**Comment by looooo** [comment]
@leoheck is this ready?

**Comment by leoheck** [comment]
If you think the image is good. I don't have any other change to do.

**Pull request merged**
